[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "VoiceRecognitionAPI"
<<<<<<< Updated upstream
versionNumber = "1.1.0"
=======
versionNumber = "1.2.0"
>>>>>>> Stashed changes
description = "Loads Windows Speech recognition into Lethal Company and provides a dev-friendly way of using it."
websiteUrl = "https://github.com/LoafOrc/VoiceRecognitionAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
willis81808-LethalSettings = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "lethalcompany", ]
[publish.categories]
lethalcompany = [ "bepinex", "tools", "libraries", "audio", ]


