[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "VoiceRecognitionAPI"
versionNumber = "2.0.0"
description = "Loads Windows Speech recognition into Lethal Company and provides a dev-friendly way of using it."
websiteUrl = "https://github.com/LoafOrc/VoiceRecognitionAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/netstandard2.1/VoiceRecognitionAPI.dll"
target = "./plugins/VoiceRecognitionAPI.dll"

[[build.copy]]
source = "./bin/Release/netstandard2.1/Resources/System.Speech.dll"
target = "./plugins/System.Speech.dll"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethalcompany", ]
[publish.categories]
lethalcompany = [ "bepinex", "tools", "libraries", "audio", ]


